# @format

name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SCOPE: "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/service.management"
  EXPIRY_DATE: 1734862536464

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: production
    env:
      CLASP_ACCESS_TOKEN: ${{ secrets.CLASP_ACCESS_TOKEN }}
      CLASP_CLIENT_ID: ${{ secrets.CLASP_CLIENT_ID }}
      CLASP_CLIENT_SECRET: ${{ secrets.CLASP_CLIENT_SECRET }}
      CLASP_ID_TOKEN: ${{ secrets.CLASP_ID_TOKEN }}
      CLASP_REFRESH_TOKEN: ${{ secrets.CLASP_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install Clasp
        run: |
          npm install --include=dev

      - name: Create clasprc.json
        run: |
          echo \{\"token\":\{\"access_token\":\"${{ env.CLASP_ACCESS_TOKEN }}\",\"scope\":\"${{ env.SCOPE }}",\"token_type\":\"Bearer\",\"id_token\":\"${{ env.CLASP_ID_TOKEN }}\",\"expiry_date\":${{ env.EXPIRY_DATE }},\"refresh_token\":\"${{ env.CLASP_REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ env.CLASP_CLIENT_ID }}\",\"clientSecret\":\"${{ env.CLASP_CLIENT_SECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":false\} > ~/.clasprc.json

      - name: Build
        run: |
          npm run build

      - name: Push
        run: |
          npm run push
