# @format

name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SCOPE: "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/service.management"
  EXPIRY_DATE: 1734862536464

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: production
    env:
      CLASP_ACCESS_TOKEN: ${{ secrets.CLASP_ACCESS_TOKEN }}
      CLASP_CLIENT_ID: ${{ secrets.CLASP_CLIENT_ID }}
      CLASP_CLIENT_SECRET: ${{ secrets.CLASP_CLIENT_SECRET }}
      CLASP_ID_TOKEN: ${{ secrets.CLASP_ID_TOKEN }}
      CLASP_REFRESH_TOKEN: ${{ secrets.CLASP_REFRESH_TOKEN }}
      GAS_SCRIPT_ID: ${{ secrets.GAS_SCRIPT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install Clasp
        run: |
          npm install --include=dev

      - name: Create clasprc.json
        run: |
          echo '{"token": {}, "oauth2ClientSettings": {}, "isLocalCreds": false}' > tmp1.json
          jq '.token += {"access_token": "${{ env.CLASP_ACCESS_TOKEN }}"}' tmp1.json > tmp2.json
          jq '.token += {"refresh_token": "${{ env.CLASP_REFRESH_TOKEN }}"}' tmp2.json > tmp3.json
          jq '.token += {"scope": "${{ env.SCOPE }}"}' tmp3.json > tmp4.json
          jq '.token += {"token_type": "Bearer"}' tmp4.json > tmp5.json
          jq '.token += {"id_token": "${{ env.CLASP_ID_TOKEN }}"}' tmp5.json > tmp6.json
          jq '.token += {"expiry_date": "${{ env.EXPIRY_DATE }}"}' tmp6.json > tmp7.json
          jq '.oauth2ClientSettings += {"clientId": "${{ env.CLASP_CLIENT_ID }}"}' tmp7.json > tmp8.json
          jq '.oauth2ClientSettings += {"clientSecret": "${{ env.CLASP_CLIENT_SECRET }}"}' tmp8.json > tmp9.json
          jq '.oauth2ClientSettings += {"redirectUri": "http://localhost"}' tmp9.json > tmp10.json
          cat tmp10.json > ~/.clasprc.json

      - name: Create clasp.json
        env:
          PWD: ${{ github.workspace }}
        run: |
          echo '{}' > clasp1.json
          jq '. + {"scriptId": "${{ env.GAS_SCRIPT_ID }}"}' clasp1.json > clasp2.json
          jq '. + {"rootDir": "${{ env.PWD }}"}' clasp2.json > clasp3.json
          cat clasp3.json > ~/.clasp.json

      - name: Build
        run: |
          npm run build

      - name: Push
        run: |
          npm run push
